python3 main.py --config-file config_one_direct.json
python3 main.py --config-file config_two_direct.json
python3 main.py --config-file config_three_direct.json
python3 main.py --config-file config_four_direct.json
python3 main.py --config-file config_five_direct.json
python3 main.py --config-file config_six_direct.json
python3 main.py --config-file config_seven_direct.json
python3 main.py --config-file config_eight_direct.json
python3 main.py --config-file config_nine_direct.json
